### ISSUE TITLE
基础使用方法？

### ISSUE THREAD

**Issue by sxjeru** [DingHanyang/chatLog#7]
经测试目前只有“user_time_online.png”可以正常导出，其他图片已无法导出。

另外请问作者用户活跃时间中的数字是指 消息条数 还是 字数？
并且其周一到周日是指从今天开始往前7天，还是……？

`最后感谢作者提供该开源项目！`

**Comment by DingHanyang** [comment]
你好，可能之前因为一些事情暂时搁置了更新，自己也是有些想法想重新构建下整个项目的，接下来会慢慢找时间，因为是学生时代写的。

1.关于其他图片无法导出问题
我刚才尝试了一下，是没有问题的，你需要依次调用charts.py里面的三个函数`ban_time()、speak_photo_in_total()和user_online_time()`然后根据自己的工程结构修改下导出的路径，当然前提是你已经执行过数据处理的程序了。

2.活跃时间中的数字是指消息条数

3.周一到周日指的是整个聊天记录文本的时间跨度中，所有的周一所有的周二以此类推所有的周天，也就是聊天记录时间跨度中的每一周的叠加。



如有其它问题可以继续保持联系。

**Comment by sxjeru** [comment]
感谢回复！

在 charts.py 末尾添加了函数调用语句，现在`ban_time`可正常导出，但是导出`speak_photo_in_total`时报错。

```
Traceback (most recent call last):
  File "C:/Users/Eru/Desktop/chatLog-master-1/chatlog/visualization/charts.py", line 130, in <module>
    chart.speak_photo_in_total()
  File "C:/Users/Eru/Desktop/chatLog-master-1/chatlog/visualization/charts.py", line 73, in speak_photo_in_total
    label="发送图片数", color="b")
  File "C:\Users\Eru\AppData\Local\Programs\Python\Python36\lib\site-packages\seaborn\_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "C:\Users\Eru\AppData\Local\Programs\Python\Python36\lib\site-packages\seaborn\categorical.py", line 3185, in barplot
    errcolor, errwidth, capsize, dodge)
  File "C:\Users\Eru\AppData\Local\Programs\Python\Python36\lib\site-packages\seaborn\categorical.py", line 1585, in __init__
    order, hue_order, units)
  File "C:\Users\Eru\AppData\Local\Programs\Python\Python36\lib\site-packages\seaborn\categorical.py", line 207, in establish_variables
    group_names)
  File "C:\Users\Eru\AppData\Local\Programs\Python\Python36\lib\site-packages\seaborn\categorical.py", line 253, in _group_longform
    grouped_vals = vals.groupby(grouper)
  File "C:\Users\Eru\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\series.py", line 1746, in groupby
    dropna=dropna,
  File "C:\Users\Eru\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\groupby\groupby.py", line 533, in __init__
    dropna=self.dropna,
  File "C:\Users\Eru\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\groupby\grouper.py", line 786, in get_grouper
    raise KeyError(gpr)
KeyError: '【发言数第一的用户昵称】'
```

最后希望能说一下 word_img.py 中需要调用的函数名，感激不尽！

**Comment by DingHanyang** [comment]
speak_photo_in_total可能是因为特殊的群马甲名，可以自行修改下。
word_img.py里面可以把longest_formation_wordcloud放进work()里面，然后直接调用work()

**Comment by sxjeru** [comment]
OK，把群等级标签删除后可正常导出条形图。

不过还是不会导出词云图……
`fp = open('../visualization/list.txt', 'r')`
问一下，上面代码中的“list.txt”里面是要放什么内容的？

**Comment by DingHanyang** [comment]
抱歉，这个我忘记说明了。
在interesting.py中有一个longest_formation函数，返回值为文件内容，具体如下
![](https://pic2.zhimg.com/80/v2-150ddcc3d812b90097d5fd09fcad13a1_1440w.png)
因为文件里面涉及一些我当时分析文本的隐私问题，就把文件删除了。

**Comment by sxjeru** [comment]
感谢答复，词云图已正常生成。

**Comment by sxjeru** [comment]
最后提个小建议，speak_photo_in_total 或许可以加上数据标签功能，另外也可以统计下表情发送次数。（消息记录里统一为 [表情]）

再次感谢作者！
